### PR TITLE
Add support for Python 3.9 and SWIG 4.0.2

### PR DESCRIPTION
**Pull request by dangtrungtin**
I updated typemap code for support Python 3.9 and SWIG 4.0.2.

### CODE REVIEW

**Comment by knonomura** [comment]
Thank you for your update.
I'll check it.

**Comment by dangtrungtin** [comment]
I'm sorry, but I found the error is happened with SWIG4.0.2.
So, I updated attribute ContainerInfo.column_info_list for SWIG 4.0.2.
And I updated Makefile, CmakeLists and README.md with new environment (Python 3.9.5, SWIG 4.0.2).

**Comment by knonomura** [comment]
Thank you for your update.
I also have an issue for Python Client with SWIG 4.0.2.
I'll try to use it.

**Comment by knonomura** [comment]
Sorry for late reply.
I merge your PR.
Thank you so much.

**Pull request merged**
